permalink: /:year:month:day/:title
url: #Your url here
baseurl:

# variables
name: 인생역전_스토리_박지훈
description: Your description here
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
